### ISSUE TITLE
Easier Solution

### ISSUE THREAD

**Issue by ios1ph** [fpsheaven/Dynamic-Windows-10-Search-bar-killer#1]
WSearch and SearchIndexer works only when WSearch service is working.
If you have SSD you can just disable WSearch service.
Cmd:
sc stop WSearch
sc config WSearch start= auto

Also disable indexing on each disk. Right click to drive -> Properties -> And disable allow indexing.
WSearch just indexing files for faster search. It is useful on HDD disks.

**Comment by fpsheaven** [comment]
There is one problem with this. I am sure that you are reffering to file searching. This is not related to that.
The search app is linked directly to the start bar. Having SearchApp.exe dead and wsearch off, you can still browse through the files. This app was created to pause the search app being opened all the time via windows 10 to provide the search in the start menu.
